[[main]]
  name = 'About'
  pageRef = '/about'
  weight = 10
  [[main]]
    name = 'Our Beliefs'
    pageRef = '/about/beliefs'
    parent = 'About'
    weight = 1
  [[main]]
    name = 'Service Times'
    pageRef = '/about/services'
    parent = 'About'
    weight = 2
  [[main]]
    name = 'Meet Our Teams'
    pageRef = '/about/teams'
    parent = 'About'
    weight = 3
[[main]]
  name = 'Ministries'
  pageRef = '/ministries'
  weight = 20
  [[main]]
    name = 'LifeKids'
    pageRef = '/ministries/lifekids'
    parent = 'Ministries'
    weight = 1
  [[main]]
    name = 'Royal Rangers'
    pageRef = '/ministries/royalrangers'
    parent = 'Ministries'
    weight = 2
  [[main]]
    name = 'Wild Ones - Young Adults'
    pageRef = '/ministries/youngadults'
    parent = 'Ministries'
    weight = 3
[[main]]
  name = 'Resources'
  pageRef = '/resources'
  weight = 30
  [[main]]
    name = 'LifeChurch App'
    pageRef = '/resources/app'
    parent = 'Resources'
    weight = 1
  [[main]]
    name = 'Sermon Notes'
    pageRef = '/resources/notes'
    parent = 'Resources'
    weight = 2
  [[main]]
    name = 'Devotional'
    pageRef = '/resources/devotional'
    parent = 'Resources'
    weight = 3
[[main]]
  name = 'Give'
  pageRef = '/give'
  weight = 40
[[main]]
  name = 'Watch Live'
  pre = '🔴'
  pageRef = '/watch'
  weight = 50
[[main]]
  name = 'Connect'
  url = 'https://docs.google.com/forms/d/e/1FAIpQLSe-JBfqyX2Uz4dsnIi6gpnHtVXjSFGJqNIiYcJ3WC6UQgkDLQ/viewform'
  weight = 60
    [[main.params]]
      rel = 'external'
